name: checkout
on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: inst
        run: npm install
      - name: lint app
        run: npm run lint
      
